### ISSUE TITLE
Точка доступа WIFI!

### ISSUE THREAD

**Issue by Noumen56** [DerpFest-12/Updater-Stuff#3]
Добрый день! Я из России, ваши прошивки очень качественные! Моё устройство Apollo, скажите пожалуйста, в последнем обновлении медленная скорость через точку доступа wifi . можете ли вы дать рекомендации исправления? Всё остальное просто отлично, единственное только эта проблема. Буду ждать вашего ответа! Сайт сложно с моим переводом:) Поэтому в случае этого вот мой адрес почты raf2212@mail.ru

**Comment by NurKeinNeid** [comment]
I dont own this device. https://t.me/rwxrrwx is the maintainer for apollo.
